<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Actualizado' => '',
    'Autor ID' => '',
    'Clase' => '',
    'Contenido' => '',
    'Count' => '',
    'Creado' => 'Creados',
    'Descripcion' => '',
    'Enlace' => '',
    'Estado' => 'Estados',
    'Id Categoria' => '',
    'Id Menu' => 'id',
    'Id Pag' => '',
    'Imagen ID' => '',
    'Meta Code Css' => '',
    'Meta Code Js' => '',
    'Meta Description' => '',
    'Meta ID' => '',
    'Meta Keywords' => '',
    'Nombre' => '',
    'Padre' => '',
    'Slug' => '',
    'Target' => '',
    'Titulo' => '',
];
